version: '3'
services:
    #Database Container
    mariadb:
        image: bitnami/mariadb:10.6
        ports:
            - "3306:3306"
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: challenge
            MARIADB_USER: challengeuser
            MARIADB_PASSWORD: challengepassword
            TZ: Europe/Lisbon
    backend:
        image: challenge/backend
        build:
            context: ./projects/Challenge
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            connectionString: server=mariadb; port=3306; database=challenge; user=root; password=root
        depends_on:
            - mariadb